- name: Setup cAdvisor service
  include_tasks: ../../shared_tasks/tasks/init_service.yml
  vars:
    service_name: cAdvisor
    reverse_proxy: reverse_proxy.conf.j2
    config_copies:
      - src_config_path: .
