---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Infrastructure:
    - Komodo:
        href: https://komo.benanna.club/stacks
        icon: https://komo.benanna.club/favicon.ico
        description: Service deployment monitoring and management
        server: docker-socket
        container: komodo

    - Omada:
        href: https://omada.benanna.club/
        icon: https://omada.benanna.club/favicon.ico?v=2
        description: Network control plane
        server: docker-socket
        container: omada-controller

    - AdGuard:
        href: https://dns.benanna.club
        icon: https://dns.benanna.club/assets/favicon.png
        description: Private DNS
        server: docker-socket
        container: adguard

    - Monitoring:
      - Kuma Primary:
          href: https://kuma.benanna.club
          icon: https://kuma.benanna.club/favicon.ico
          description: Service monitoring and alarms. Primary instance
          server: docker-socket
          container: uptime-kuma
      - Kuma Secondary:
          href: http://192.168.0.69:3001/
          icon: https://kuma.benanna.club/favicon.ico
          description: Service monitoring and alarms. Secondary instance
          siteMonitor: http://192.168.0.69:3001/

- Services:
    - Home Assistant:
        href: https://ha.benanna.club
        icon: https://ha.benanna.club/static/icons/favicon.ico
        description: Home automation and control
        server: docker-socket
        container: homeassistant
    - Immich:
        href: https://immich.benanna.club
        icon: https://immich.benanna.club/favicon.ico
        description: Photo organization and gallery
        server: docker-socket
        container: immich_server
    - Seafile:
        href: https://seafile.benanna.club
        icon: https://seafile.benanna.club/media/favicons/favicon.png
        description: File synchronization and backup
        server: docker-socket
        container: seafile
    - NVR:
        href: https://192.168.0.10/
        icon: https://192.168.0.10/favicon.ico
        description: Camera feeds and recordings
        siteMonitor: https://192.168.0.10/
    - Code:
        href: https://code.benanna.club
        icon: /icons/vscode.png
        description: Browser based VS Code instance
        server: docker-socket
        container: code-server

- Home Audio:
    - Snapcast:
        href: https://snapcast.benanna.club
        icon: https://snapcast.benanna.club/logo.svg
        description: Audio zone volume and input selection
        server: docker-socket
        container: snapserver
    - Fireplace Zone:
        href: http://192.168.0.200/
        icon: mdi-cast-audio-#5191e0
        description: Audio zone in the game room
        siteMonitor: http://192.168.0.200/
    - Dining Room Zone:
        href: http://192.168.0.202/
        icon: mdi-cast-audio-#5191e0
        description: Audio zone in the dining room
        siteMonitor: http://192.168.0.202/
    - Office Zone:
        href: http://192.168.0.205/
        icon: mdi-cast-audio-#5191e0
        description: Audio zone in the upstairs office
        siteMonitor: http://192.168.0.205/
    - Bedroom Zone:
        href: http://192.168.0.204/
        icon: mdi-cast-audio-#5191e0
        description: Audio zone in the bedroom
        siteMonitor: http://192.168.0.204/
    - Bathroom Zone:
        href: http://192.168.0.203/
        icon: mdi-cast-audio-#5191e0
        description: Audio zone in the upstairs bathroom
        siteMonitor: http://192.168.0.203/
