title: BenAnna Mission Control
description: Control plane for the homelab
language: en
target: _blank

showStats: true
statusStyle: "dot"

theme: dark
color: slate

useEqualHeights: true
layout:
  Core:
    style: row
    columns: 2
    Infrastructure:
      style: row
      columns: 3
    Monitoring:
      style: row
      columns: 3
  Services:
    style: row
    columns: 6
  Home Audio:
    style: row
    columns: 4
  Zones:
    style: row
    columns: 2
    header: false
    Downstairs Zones:
      style: row
      columns: 3
    Upstairs Zones:
      style: row
      columns: 3
  BottomRow:
    header: false
    style: row
    columns: 3
    Backups:
      style: row
      columns: 2
    Energy:
      style: row
      columns: 1
    Bots:
      style: row
      columns: 1
  

headerStyle: boxed
background:
  image: /images/background.jpg
  saturate: 200
  opacity: 20
