timezone: EST
root_domain: benanna.club
docker_network_subnet: 172.20.0.0/16
service_user: homelab
service_group: homelab
logs_path: /opt/homelab/logs
secondary_host_ip: 192.168.0.69

extra_domains:
  - sirgeorgelordofthevoid.com

services_config_path: /opt/homelab/service-configs
services_data_path: "{{ data_path }}/service-data"
enabled_services:
  - Redbot
  - Seafile
  - Immich
  - ddns
  - HomeAssistant
  - Omada
  - Kuma
  - Snapserver
  - mSync
  - Mealie
  - Homepage

crons_config_path: /opt/homelab/cron-configs
crons_data_path: "{{ data_path }}/cron-data"
enabled_crons:
  - Certbot
  - GithubMirror
  - Backups

seafile:
  clone_path: "{{ data_path }}/seafile-clone"
  # from https://customer.seafile.com/downloads
  docker_username: seafile

msync_music_path: "{{ seafile.clone_path }}/Music"

immich:
  immich_version: release
  db_hostname: immich_postgres
  db_username: postgres
  db_database_name: immich
  redis_hostname: immich_redis

nginx:
  config_local_path: config
  config_path: "{{ services_config_path }}/Nginx/config"
  certs_path: "{{ services_data_path }}/Nginx/certs"
  letsencrypt_lib_path: "{{ services_data_path }}/Nginx/letsencrypt"
  cloudflare_credentials_path: "{{ services_config_path }}/Nginx/cloudflare.ini"
  logs_path: "{{ logs_path }}/nginx"

homeassistant:
  conf_path: "{{ services_data_path }}/HomeAssistant/config"

github_mirror:
  repo_path: "{{ crons_data_path }}/GithubMirror"
  repo_list:
    - name: Homelab
      repo_url: "https://github.com/benreid24/Homelab.git"
    - name: BLIB
      repo_url: "https://github.com/benreid24/BLIB.git"
    - name: RPS-Godot
      repo_url: "https://github.com/benreid24/RPS-Godot.git"
    - name: FriendCal
      repo_url: "https://github.com/benreid24/FriendCal.git"
    - name: Outpost-Engine
      repo_url: "https://github.com/benreid24/Outpost-Engine.git"
    - name: Stellaru
      repo_url: "https://github.com/benreid24/Stellaru.git"
    - name: BLIB-Template
      repo_url: "https://github.com/benreid24/BLIB-Template.git"
    - name: Peoplemon-3
      repo_url: "https://github.com/benreid24/Peoplemon-3.git"
    - name: FastCopy
      repo_url: "https://github.com/benreid24/FastCopy.git"
    - name: Minecraft-Runner
      repo_url: "https://github.com/benreid24/Minecraft-Runner.git"
    - name: Animation-Editor-2
      repo_url: "https://github.com/benreid24/Animation-Editor-2.git"
    - name: Oatmeal
      repo_url: "https://github.com/benreid24/Oatmeal.git"
    - name: Wedding-Website
      repo_url: "https://github.com/benreid24/wedding-site.git"
    - name: Space-Race
      repo_url: "https://github.com/benreid24/Space-Race.git"
    - name: Ignis-Cor
      repo_url: "https://github.com/benreid24/Ignus-Cor.git"
    - name: Rover
      repo_url: "https://github.com/benreid24/Rover.git"
    - name: Peoplemon
      repo_url: "https://github.com/benreid24/Peoplemon.git"
    - name: Animation-Editor
      repo_url: "https://github.com/benreid24/Animation-Editor.git"
    - name: 22ndCG-Website
      repo_url: "https://github.com/benreid24/22ndCG-Website.git"
    - name: Personal-Website
      repo_url: "https://github.com/benreid24/Personal-Website.git"
    - name: QuadPilot
      repo_url: "https://github.com/benreid24/QuadPilot.git"

satisfactory_saves_path: "{{ data_path }}/satisfactory-saves"

backups:
  creds_file: /etc/smb-credentials

  onsite_server_address: "{{ secondary_host_ip }}"
  onsite_server_path: "//{{ secondary_host_ip }}/WOGH"
  onsite_mount_path: "/mnt/backup-onsite"
  onsite_start_monitor_a: "http://{{ secondary_host_ip }}:3001/api/push/f63QYckSwV?status=up&msg=OK&ping="
  onsite_start_monitor_b: "https://kuma.benanna.club/api/push/IOmy1Ktinig9TjEx4x1eR8NYLFq4DgUG?status=up&msg=OK&ping="
  onsite_end_monitor_a: "https://kuma.benanna.club/api/push/o7vgqb2AIxxda1Jyg23xVJt1PdeBNTdD?status=up&msg=OK"
  onsite_end_monitor_b: "http://{{ secondary_host_ip }}:3001/api/push/2v3FEsIt3J?status=up&msg=OK"

  offsite_server_address: 192.168.0.42
  offsite_server_path: "//192.168.0.42/offsite-drive"
  offsite_mount_path: "/mnt/backup-offsite"
  offsite_start_monitor_a: "http://{{ secondary_host_ip }}:3001/api/push/Tf3kcpNdai?status=up&msg=OK&ping="
  offsite_start_monitor_b: "https://kuma.benanna.club/api/push/D3ZOW2KPNkvQFnVWbziLzfHbZiq6bVhJ?status=up&msg=OK&ping="
  offsite_end_monitor_a: "https://kuma.benanna.club/api/push/uEWiN88WDt670itRJYFGVaKsx2adQ07W?status=up&msg=OK"
  offsite_end_monitor_b: "http://{{ secondary_host_ip }}:3001/api/push/gVJzrifnKH?status=up&msg=OK"
