push_monitor_token: "not-secret"

push_monitor_hosts:
  - "gatus.{{ overseer_hostname }}"
  - "gatus.{{ onsite_pi_hostname }}"
  - "gatus.{{ offsite_pi_hostname }}"

common_monitored_endpoints:
  - name: "Reachable: benanna.club"
    url: "https://benanna.club"
    method: GET
    interval: 60s
    group: "DNS"
    conditions:
      - "[STATUS] == any(200, 204)"
      - "[CERTIFICATE_EXPIRATION] > 48h"
  - name: "Reachable: sirgeorgelordofthevoid.com"
    url: "https://sirgeorgelordofthevoid.com"
    method: GET
    interval: 60s
    group: "DNS"
    conditions:
      - "[STATUS] == any(200, 204)"
      - "[CERTIFICATE_EXPIRATION] > 48h"

  - name: "NVR"
    url: "http://nvr.{{ overseer_hostname }}"
    method: GET
    interval: 60s
    group: "Services"

  - name: "Overseer"
    url: "https://{{ overseer_hostname }}"
    interval: 60s
    group: "Servers"
    conditions:
      - "[STATUS] == any(200, 204)"
      - "[CERTIFICATE_EXPIRATION] > 48h"
  - name: "Onsite Pi"
    url: "https://{{ onsite_pi_hostname }}"
    interval: 60s
    group: "Servers"
    conditions:
      - "[STATUS] == any(200, 204)"
      - "[CERTIFICATE_EXPIRATION] > 48h"
  - name: "Offsite Pi"
    url: "https://{{ offsite_pi_hostname }}"
    interval: 60s
    group: "Servers"
    conditions:
      - "[STATUS] == any(200, 204)"
      - "[CERTIFICATE_EXPIRATION] > 48h"

  - name: "Game Room Audio Zone"
    url: "icmp://192.168.0.200"
    interval: 60s
    group: "Audio Zones"
    conditions:
      - "[CONNECTED] == true"
  - name: "Dining Room Audio Zone"
    url: "icmp://192.168.0.202"
    interval: 60s
    group: "Audio Zones"
    conditions:
      - "[CONNECTED] == true"
  - name: "Upstairs Bathroom Audio Zone"
    url: "icmp://192.168.0.203"
    interval: 60s
    group: "Audio Zones"
    conditions:
      - "[CONNECTED] == true"
  - name: "Bedroom Audio Zone"
    url: "icmp://192.168.0.204"
    interval: 60s
    group: "Audio Zones"
    conditions:
      - "[CONNECTED] == true"
  - name: "Office Audio Zone"
    url: "icmp://192.168.0.205"
    interval: 60s
    group: "Audio Zones"
    conditions:
      - "[CONNECTED] == true"
