timezone: America/New_York
root_domain: benanna.club
docker_network_subnet: 172.20.0.0/16
docker_network_ip_range: 172.20.1.0/24
nginx_docker_ip: 172.20.0.10
service_user: homelab
service_group: homelab
logs_path: /opt/homelab/logs

overseer_ip: 192.168.0.100
overseer_hostname: "{{ root_domain }}"
onsite_pi_ip: 192.168.0.69
onsite_pi_hostname: "pi.{{ root_domain }}"
offsite_pi_ip: 192.168.0.42
offsite_pi_hostname: "garage-pi.{{ root_domain }}"

primary_dns_ip: "{{ overseer_ip }}"
secondary_dns_ip: "{{ onsite_pi_ip }}"

extra_domains: []

cache_path: /opt/homelab/cache
services_config_path: /opt/homelab/service-configs
services_data_path: "{{ data_path }}/service-data"

crons_config_path: /opt/homelab/cron-configs
crons_data_path: "{{ data_path }}/cron-data"
