timezone: EST
root_domain: benanna.club
docker_network_subnet: 172.20.0.0/16
service_user: homelab
service_group: homelab
logs_path: /opt/homelab/logs

overseer_ip: 192.168.0.100
overseer_hostname: "{{ root_domain }}"
onsite_pi_ip: 192.168.0.69
onsite_pi_hostname: "pi.{{ root_domain }}"
offsite_pi_ip: 192.168.0.42

primary_dns_ip: "{{ overseer_ip }}"
secondary_dns_ip: "{{ onsite_pi_ip }}"

extra_domains: []

services_config_path: /opt/homelab/service-configs
services_data_path: "{{ data_path }}/service-data"

crons_config_path: /opt/homelab/cron-configs
crons_data_path: "{{ data_path }}/cron-data"

seafile:
  clone_path: "{{ data_path }}/seafile-clone"
  # from https://customer.seafile.com/downloads
  docker_username: seafile

msync_music_path: "{{ seafile.clone_path }}/Music"

immich:
  immich_version: release
  db_hostname: immich_postgres
  db_username: postgres
  db_database_name: immich
  redis_hostname: immich_redis

nginx:
  config_local_path: config
  config_path: "{{ services_config_path }}/Nginx/config"
  sites_enabled_path: "{{ services_config_path }}/Nginx/config/sites-enabled"
  certs_path: "{{ services_data_path }}/Nginx/certs"
  letsencrypt_lib_path: "{{ services_data_path }}/Nginx/letsencrypt"
  cloudflare_credentials_path: "{{ services_config_path }}/Nginx/cloudflare.ini"
  logs_path: "{{ logs_path }}/nginx"

homeassistant:
  conf_path: "{{ services_data_path }}/HomeAssistant/config"

github_mirror:
  repo_path: "{{ crons_data_path }}/GithubMirror"
  repo_list:
    - name: Homelab
      repo_url: "https://github.com/benreid24/Homelab.git"
    - name: BLIB
      repo_url: "https://github.com/benreid24/BLIB.git"
    - name: RPS-Godot
      repo_url: "https://github.com/benreid24/RPS-Godot.git"
    - name: FriendCal
      repo_url: "https://github.com/benreid24/FriendCal.git"
    - name: Outpost-Engine
      repo_url: "https://github.com/benreid24/Outpost-Engine.git"
    - name: Stellaru
      repo_url: "https://github.com/benreid24/Stellaru.git"
    - name: BLIB-Template
      repo_url: "https://github.com/benreid24/BLIB-Template.git"
    - name: Peoplemon-3
      repo_url: "https://github.com/benreid24/Peoplemon-3.git"
    - name: FastCopy
      repo_url: "https://github.com/benreid24/FastCopy.git"
    - name: Minecraft-Runner
      repo_url: "https://github.com/benreid24/Minecraft-Runner.git"
    - name: Animation-Editor-2
      repo_url: "https://github.com/benreid24/Animation-Editor-2.git"
    - name: Oatmeal
      repo_url: "https://github.com/benreid24/Oatmeal.git"
    - name: Wedding-Website
      repo_url: "https://github.com/benreid24/wedding-site.git"
    - name: Space-Race
      repo_url: "https://github.com/benreid24/Space-Race.git"
    - name: Ignis-Cor
      repo_url: "https://github.com/benreid24/Ignus-Cor.git"
    - name: Rover
      repo_url: "https://github.com/benreid24/Rover.git"
    - name: Peoplemon
      repo_url: "https://github.com/benreid24/Peoplemon.git"
    - name: Animation-Editor
      repo_url: "https://github.com/benreid24/Animation-Editor.git"
    - name: 22ndCG-Website
      repo_url: "https://github.com/benreid24/22ndCG-Website.git"
    - name: Personal-Website
      repo_url: "https://github.com/benreid24/Personal-Website.git"
    - name: QuadPilot
      repo_url: "https://github.com/benreid24/QuadPilot.git"

satisfactory_saves_path: "{{ data_path }}/satisfactory-saves"

backups:
  creds_file: /etc/smb-credentials

  onsite_server_address: "{{ onsite_pi_ip }}"
  onsite_server_path: "//{{ onsite_pi_ip }}/WOGH"
  onsite_mount_path: "/mnt/backup-onsite"
  onsite_start_monitor_a: "http://{{ onsite_pi_ip }}:3001/api/push/mtaiYPr8ZMEwQEtDQsPxFmPS5JUCpQgZ?status=up&msg=OK&ping="
  onsite_start_monitor_b: "https://kuma.benanna.club/api/push/IOmy1Ktinig9TjEx4x1eR8NYLFq4DgUG?status=up&msg=OK&ping="
  onsite_end_monitor_a: "https://kuma.benanna.club/api/push/o7vgqb2AIxxda1Jyg23xVJt1PdeBNTdD?status=up&msg=OK"
  onsite_end_monitor_b: "http://{{ onsite_pi_ip }}:3001/api/push/LQpDNOkCyKpq2SU8r7vbZRKqGsmfOSUc?status=up&msg=OK"

  offsite_server_address: "{{ offsite_pi_ip }}"
  offsite_server_path: "//{{ offsite_pi_ip }}/offsite-drive"
  offsite_mount_path: "/mnt/backup-offsite"
  offsite_start_monitor_a: "http://{{ onsite_pi_ip }}:3001/api/push/9ym67fWxhE9RPENoafJkAEv4CtacyZn6?status=up&msg=OK&ping="
  offsite_start_monitor_b: "https://kuma.benanna.club/api/push/D3ZOW2KPNkvQFnVWbziLzfHbZiq6bVhJ?status=up&msg=OK&ping="
  offsite_end_monitor_a: "https://kuma.benanna.club/api/push/uEWiN88WDt670itRJYFGVaKsx2adQ07W?status=up&msg=OK"
  offsite_end_monitor_b: "http://{{ onsite_pi_ip }}:3001/api/push/kXUtPyhoMD4bVJdBiU6I0rFa3BNvOG0C?status=up&msg=OK"
