data_path: /opt/homelab/data

pretty_hostname: Offsite Pi
host_ip: "{{ offsite_pi_ip }}"
external_hostname: "{{ offsite_pi_hostname }}"

managed_domains: "{{ [external_hostname] }}"
certbot_env: prod

komodo_deployment_mode: periphery-only

samba_disk_uuid: "511308952E659B6F"
samba_mount_point: "/mnt/backup-disk"
samba_share_name: "offsite-drive"
samba_share_path: "/mnt/backup-disk"
samba_user: "{{ smb_username }}"
samba_password: "{{ smb_password }}"
samba_create_mask: "0755"
samba_directory_mask: "0755"

homepage_data_volume: /mnt/backup-disk

seafile:
  clone_path: /mnt/backup-disk/seafile-clone
