services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    volumes:
      - ${DATA_PATH}/config:/app/config
      - ${DATA_PATH}/images:/app/public/images
      - ${DATA_PATH}/icons:/app/public/icons
      - ${HOMEPAGE_DATA_VOLUME}:/mnt/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      HOMEPAGE_ALLOWED_HOSTS: ${HOSTNAME}
    networks:
      - homelab

networks:
  homelab:
    external: true
