data_path: /opt/homelab/data

pretty_hostname: Onsite Pi
external_hostname: "{{ onsite_pi_hostname }}"
host_ip: "{{ onsite_pi_ip }}"

managed_domains: "{{ [external_hostname] }}"
certbot_env: prod

primary_dns_ip: "{{ host_ip }}"
secondary_dns_ip: "{{ overseer_ip }}"

komodo_deployment_mode: periphery-only

samba_disk_uuid: "7A0A96B6499D1C74"
samba_mount_point: "/mnt/backup-disk"
samba_share_name: "WOGH"
samba_share_path: "/mnt/backup-disk/Share"
samba_user: "{{ smb_username }}"
samba_password: "{{ smb_password }}"
samba_create_mask: "0755"
samba_directory_mask: "0755"
