external_hostname: "{{ root_domain }}"
managed_domains: "{{ [external_hostname] + extra_domains }}"
data_path: /mnt/data/homelab/data
certbot_env: prod
backup_dst_path: "/homelab-backups"
spotify_audio_name: "Home%20Audio"
spotify_audio_name_pretty: "Home Audio"
prompt_to_restart_services: true
host_ip: 192.168.0.100
