services:
  db:
    restart: unless-stopped
    image: mariadb:10.11
    container_name: seafile-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_LOG_CONSOLE=true
      - MARIADB_AUTO_UPGRADE=1
    volumes:
      - ${DATA_PATH}/mysql/db:/var/lib/mysql # Requested, specifies the path to MySQL data persistent store.
    networks:
      - seafile-net

  memcached:
    restart: unless-stopped
    image: memcached:1.6.18
    container_name: seafile-memcached
    entrypoint: memcached -m 256
    networks:
      - seafile-net

  elasticsearch:
    restart: unless-stopped
    image: elasticsearch:8.13.0
    container_name: seafile-elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - "xpack.security.enabled=false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 4g
    volumes:
      - ${DATA_PATH}/elasticsearch/data:/usr/share/elasticsearch/data # Requested, specifies the path to Elasticsearch data persistent store.
    networks:
      - seafile-net

  seafile:
    restart: unless-stopped
    image: docker.seadrive.org/seafileltd/seafile-pro-mc:latest
    container_name: seafile
    volumes:
      - ${DATA_PATH}/data:/shared # Requested, specifies the path to Seafile data persistent store.
    environment:
      - DB_HOST=db
      - DB_ROOT_PASSWD=${DB_PASSWORD}
      - TIME_ZONE=America/New_York
      - SEAFILE_ADMIN_EMAIL=${ADMIN_EMAIL}
      - SEAFILE_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - SEAFILE_SERVER_LETSENCRYPT=false
      - SEAFILE_SERVER_HOSTNAME=${HOSTNAME}
    depends_on:
      - db
      - memcached
      - elasticsearch
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api2/ping/"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    networks:
      - seafile-net
      - homelab
    cap_add:
      - SYS_ADMIN

  seafile-client:
    build:
      context: ./seafile-cli
      dockerfile: Dockerfile
    container_name: seafile-client
    restart: unless-stopped
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - SEAFILE_CLI_SERVER_URL=${SEAFILE_CLI_SERVER_URL}
      - SEAFILE_CLI_USERNAME=${SEAFILE_CLI_USERNAME}
      - SEAFILE_CLI_TOKEN=${SEAFILE_CLI_TOKEN}
      - SEAFILE_CLI_LIBRARY_IDS=${SEAFILE_CLI_LIBRARY_IDS}
      - SEAFILE_CLI_DATA_DIR=/data
      - SEAFILE_CLI_CONFIG_DIR=/config
    volumes:
      - ${SEAFILE_CLI_CONFIG_PATH}:/config
      - ${SEAFILE_CLI_CLONE_PATH}:/data
    networks:
      - seafile-net
    depends_on:
      - seafile

networks:
  seafile-net:
  homelab:
    external: true
