monitored_endpoints:
  - name: "Gatus {{ pretty_hostname }}"
    url: "https://gatus.{{ external_hostname }}"
    method: GET
    interval: 60s
    group: "Monitoring"

  - name: "AdGuard Primary"
    url: "https://dns.{{ external_hostname }}"
    method: GET
    interval: 60s
    group: "Infrastructure"

  - name: "Komodo"
    url: "https://komo.{{ external_hostname }}"
    method: GET
    interval: 60s
    group: "Infrastructure"

  - name: "Omada Controller"
    url: "https://omada.{{ external_hostname }}"
    method: GET
    interval: 60s
    group: "Infrastructure"

  - name: "Home Assistant"
    url: "https://ha.{{ external_hostname }}"
    method: GET
    interval: 60s
    group: "Services"

  - name: "Immich"
    url: "https://immich.{{ external_hostname }}"
    method: GET
    interval: 60s
    group: "Services"

  - name: "Seafile"
    url: "https://seafile.{{ external_hostname }}"
    method: GET
    interval: 60s
    group: "Services"

  - name: "Mealie"
    url: "https://mealie.{{ external_hostname }}"
    method: GET
    interval: 60s
    group: "Services"

  - name: "Leantime"
    url: "https://leantime.{{ external_hostname }}"
    method: GET
    interval: 60s
    group: "Services"

  - name: "Snapcast"
    url: "https://snapcast.{{ external_hostname }}"
    method: GET
    interval: 60s
    group: "Services"

  - name: "Jellyfin"
    url: "https://jellyfin.{{ external_hostname }}"
    method: GET
    interval: 60s
    group: "Services"

  - name: "Jellyseerr"
    url: "https://jellyseerr.{{ external_hostname }}"
    method: GET
    interval: 60s
    group: "Services"

  - name: "Bazarr"
    url: "https://bazarr.{{ external_hostname }}"
    method: GET
    interval: 60s
    group: "Services"

  - name: "Sonarr"
    url: "https://sonarr.{{ external_hostname }}"
    method: GET
    interval: 60s
    group: "Services"
  
  - name: "Radarr"
    url: "https://radarr.{{ external_hostname }}"
    method: GET
    interval: 60s
    group: "Services"

  - name: "Prowlarr"
    url: "https://prowlarr.{{ external_hostname }}"
    method: GET
    interval: 60s
    group: "Services"

  - name: "FlareSolverr"
    url: "https://flaresolverr.{{ external_hostname }}"
    method: GET
    interval: 60s
    group: "Services"
  
  - name: "qBittorrent"
    url: "https://qbit.{{ external_hostname }}"
    method: GET
    interval: 60s
    group: "Services"

  - name: "mSync UI"
    url: "https://msync.{{ external_hostname }}"
    method: GET
    interval: 60s
    group: "Music Sync"

  - name: "cAdvisor - Overseer"
    url: "https://cadvisor.{{ external_hostname }}"
    method: GET
    interval: 60s
    group: "Monitoring"

  - name: "GPU Exporter - Overseer"
    url: "https://gpu-prom.{{ external_hostname }}"
    method: GET
    interval: 60s
    group: "Monitoring"

  - name: "Node Exporter - Overseer"
    url: "http://{{ overseer_ip }}:9100/metrics"
    method: GET
    interval: 60s
    group: "Monitoring"

  - name: "Prometheus"
    url: "https://prometheus.{{ external_hostname }}"
    method: GET
    interval: 60s
    group: "Monitoring"

  - name: "Grafana"
    url: "https://grafana.{{ external_hostname }}"
    method: GET
    interval: 60s
    group: "Monitoring"

push_monitors:
  - name: "mSync Scanned"
    group: "Music Sync"
    interval: "1200s"

  - name: "{{ backups.servers[0].start_key }}"
    group: "{{ backups.monitor_group }}"
    interval: "4800s"
  - name: "{{ backups.servers[0].end_key }}"
    group: "{{ backups.monitor_group }}"
    interval: "4800s"

  - name: "{{ backups.servers[0].check_start_key }}"
    group: "{{ backups.monitor_group }}"
    interval: "14400s"
  - name: "{{ backups.servers[0].check_end_key }}"
    group: "{{ backups.monitor_group }}"
    interval: "14400s"

  - name: "{{ backups.servers[1].start_key }}"
    group: "{{ backups.monitor_group }}"
    interval: "4800s"
  - name: "{{ backups.servers[1].end_key }}"
    group: "{{ backups.monitor_group }}"
    interval: "4800s"

  - name: "{{ backups.servers[1].check_start_key }}"
    group: "{{ backups.monitor_group }}"
    interval: "14400s"
  - name: "{{ backups.servers[1].check_end_key }}"
    group: "{{ backups.monitor_group }}"
    interval: "14400s"

  - name: "Raid Array Health"
    group: "{{ backups.monitor_group }}"
    interval: "65s"
