- name: "Install required packages for backup jobs"
  ansible.builtin.package:
    name:
      - cifs-utils
      - bzip2
    state: present
  become: true

- name: "Write SMB credentials file"
  ansible.builtin.copy:
    dest: "{{ backups.creds_file }}"
    content: |
      username={{ smb_username }}
      password={{ smb_password }}
    owner: root
    group: root
    mode: "0600"
  become: true

- name: "Ensure Backups cron config directory exists"
  ansible.builtin.file:
    path: "{{ crons_config_path }}/Backups"
    state: directory
    owner: "{{ service_user }}"
    group: "{{ service_group }}"
    mode: "0755"
  become: true

- name: "Download restic binary"
  ansible.builtin.get_url:
    url: "https://github.com/restic/restic/releases/download/v0.18.1/restic_0.18.1_linux_amd64.bz2"
    dest: "{{ crons_config_path }}/Backups/restic.bz2"
    owner: "{{ service_user }}"
    group: "{{ service_group }}"
    mode: "0755"
  become: true

- name: "Decompress restic binary"
  ansible.builtin.shell: >
    bzip2 -d {{ crons_config_path }}/Backups/restic.bz2
  args:
    creates: "{{ crons_config_path }}/Backups/restic"
  become: true

- name: "Set restic binary permissions"
  ansible.builtin.file:
    path: "{{ crons_config_path }}/Backups/restic"
    owner: "{{ service_user }}"
    group: "{{ service_group }}"
    mode: "0755"
  become: true

- name: "Write restic backup passkey command file"
  ansible.builtin.copy:
    dest: "{{ crons_config_path }}/Backups/restic_passcommand.sh"
    content: |
      #!/bin/sh
      echo "{{ restic_backup_passphrase }}"
    owner: root
    group: root
    mode: "0700"
  become: true

- name: "Set up backup servers"
  include_tasks: setup_backup.yml
  vars:
    backup: "{{ server }}"
  loop: "{{ backups.servers }}"
  loop_control:
    loop_var: server
