all:
  children:
    homelab:
      hosts:
        overseer:
          ansible_host: 192.168.0.100
          ansible_user: ben
        onsite_pi:
          ansible_host: 192.168.0.69
          ansible_user: ben
        offsite_pi:
          ansible_host: 192.168.0.42
          ansible_user: ben
