- name: Setup Kuma service
  include_tasks: ../shared_tasks/tasks/init_service.yml
  vars:
    service_name: Kuma
    env_content: |
      DATA_PATH={{ services_data_path }}/Kuma
    templates:
      - src_template_path: docker-compose.yml.j2
        dst_template_path: docker-compose.yml
        file_mode: "0644"
