- name: Setup Kuma service
  include_tasks: ../shared_tasks/tasks/init_service.yml
  vars:
    service_name: Kuma
    config_copies:
      - src_config_path: .
    env_content: |
      DATA_PATH={{ services_data_path }}/Kuma
