services:
  seafile-client:
    build:
      context: .
      dockerfile: ${BUILD_CTX}/Dockerfile
    container_name: seafile-client
    restart: unless-stopped
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    environment:
      - SEAFILE_CLI_SERVER_URL=${SEAFILE_CLI_SERVER_URL}
      - SEAFILE_CLI_USERNAME=${SEAFILE_CLI_USERNAME}
      - SEAFILE_CLI_PASSWORD=${SEAFILE_CLI_PASSWORD}
      - SEAFILE_CLI_LIBRARY_IDS=${SEAFILE_CLI_LIBRARY_IDS}
      - SEAFILE_CLI_USE_TOKEN=${SEAFILE_CLI_USE_TOKEN:-false}
      - SEAFILE_CLI_DATA_DIR=/data
      - SEAFILE_CLI_CONFIG_DIR=/config
    volumes:
      - ${SEAFILE_CLI_CONFIG_PATH}:/config
      - ${SEAFILE_CLI_CLONE_PATH}:/data
