title: BenAnna Mission Control
description: Control plane for the homelab
language: en
target: _blank

showStats: true
statusStyle: "dot"

theme: dark
color: slate

useEqualHeights: true
layout:
  Services:
    style: row
    columns: 5
  Media:
    style: row
    columns: 6
  MiddleRow:
    style: row
    columns: 6
    header: false
    Home Audio:
      style: row
      columns: 1
    Downstairs Zones:
      style: column
      rows: 3
    Upstairs Zones:
      style: column
      rows: 3
    Audio Infrastructure:
      style: column
      rows: 3
    File Sync:
      style: column
      rows: 3
    Certbots:
      style: column
      rows: 3
  Infrastructure:
    style: row
    columns: 6
  BottomRow:
    header: false
    style: row
    columns: 2
    LeftColumn:
      style: row
      columns: 3
      header: false
    Monitoring:
      style: row
      columns: 3

headerStyle: boxed
background:
  image: /images/background.jpg
  saturate: 200
  opacity: 20
