title: BenAnna Mission Control
description: Control plane for the homelab
language: en
target: _blank

showStats: true
statusStyle: "dot"

theme: dark
color: slate

useEqualHeights: true
layout:
  Services:
    style: row
    columns: 4
  MediaRow:
    style: row
    columns: 5
    header: false
    Media:
      style: column
      rows: 2
    Acquisition:
      style: column
      rows: 2
    " ":
      style: column
      rows: 2
    Indexing:
      style: column
      rows: 2
    Torrenting:
      style: column
      rows: 2
  MiddleRow:
    style: row
    columns: 6
    header: false
    Home Audio:
      style: row
      columns: 1
    Downstairs Zones:
      style: column
      rows: 3
    Upstairs Zones:
      style: column
      rows: 3
    Audio Infrastructure:
      style: column
      rows: 3
    File Sync:
      style: column
      rows: 3
    Certbots:
      style: column
      rows: 3
  Infrastructure:
    style: row
    columns: 6
  Monitoring & Observability:
    style: row
    columns: 6

headerStyle: boxed
background:
  image: /images/background.jpg
  saturate: 200
  opacity: 20
