- name: Gather facts from all homelab hosts
  hosts: homelab
  gather_facts: true
  tasks: []

- name: Provision Offsite Pi
  hosts: offsite_pi
  become: true

  roles:
    - common
    - docker
    - docker_proxy
    - smb_host
    - service_nginx
    - service_komodo
    - service_seafile_client
    - service_homepage
    - service_gatus

- name: Provision Onsite Pi
  hosts: onsite_pi
  become: true

  roles:
    - common
    - docker
    - docker_proxy
    - smb_host
    - service_nginx
    - service_adguard
    - service_komodo
    - service_seafile_client
    - service_homepage
    - service_gatus

- name: Provision Overseer
  hosts: overseer
  become: true

  roles:
    - common
    - docker
    - docker_proxy
    - service_adguard
    - service_nginx
    - service_komodo
    - service_redbot
    - service_jellyfin
    - service_qbittorrent
    - service_seafile
    - service_seafile_client
    - service_immich
    - service_ddns
    - service_homeassistant
    - service_omada
    - service_snapcast
    - service_msync
    - service_mealie
    - service_leantime
    - service_homepage
    - cron_backups
    - cron_github_mirror
    - cron_raid_check
    - steam
    - satisfactory
    - service_gatus
