- name: Provision Overseer
  hosts: overseer
  become: true

  roles:
    - common
    - docker
    - service_adguard
    - service_nginx
    - service_komodo
    # - services
    # - crons
    # - steam
    # - satisfactory
