- name: Provision Onsite Pi
  hosts: onsite_pi
  become: true

  roles:
    - common
    - docker
    - smb_host
    - service_adguard
    - service_kuma

- name: Provision Overseer
  hosts: overseer
  become: true

  roles:
    - common
    - docker
    - service_adguard
    - service_nginx
    - service_komodo
    - service_redbot
    - service_seafile
    - service_immich
    - service_ddns
    - service_homeassistant
    - service_omada
    - service_kuma
    - service_snapcast
    - service_msync
    - service_mealie
    - service_homepage
    - cron_backups
    - cron_github_mirror
    - steam
    - satisfactory
