- name: Setup Immich service
  include_tasks: ../../shared_tasks/tasks/init_service.yml
  vars:
    service_name: Immich
    reverse_proxy: reverse_proxy.conf.j2
    skip_chown_data: true
    env_content: |
      IMMICH_VERSION={{ immich.immich_version }}
      UPLOAD_LOCATION={{ services_data_path }}/Immich/library
      DB_DATA_LOCATION={{ services_data_path }}/Immich/database
      CACHE_LOCATION={{ services_data_path }}/Immich/cache
      DB_HOSTNAME={{ immich.db_hostname }}
      DB_USERNAME={{ immich.db_username }}
      DB_DATABASE_NAME={{ immich.db_database_name }}
      DB_PASSWORD={{ immich_db_password }}
      REDIS_HOSTNAME={{ immich.redis_hostname }}
      EXTERNAL_PATH={{ seafile.clone_path }}
    config_copies:
      - src_config_path: .
