- name: Create Librespot cache directories
  ansible.builtin.file:
    path: "{{ services_config_path }}/Snapcast/librespot/{{ librespot_dir }}"
    state: directory
    owner: "{{ service_user }}"
    group: "{{ service_group }}"
    mode: '0755'
  become: true
  loop:
    - cache
    - syscache
    - user
  loop_control:
    loop_var: librespot_dir

- name: Write Librespot Spotify credentials file
  ansible.builtin.copy:
    dest: "{{ services_config_path }}/Snapcast/librespot/syscache/credentials.json"
    owner: "{{ service_user }}"
    group: "{{ service_group }}"
    mode: '0600'
    content: |
      {
        "username": "{{ spotify_username }}",
        "auth_data": "{{ spotify_password }}",
        "auth_type": 1
      }
  become: true

- name: Create MPD data directory
  ansible.builtin.file:
    path: "{{ services_data_path }}/Snapcast/MPD"
    state: directory
    owner: "{{ service_user }}"
    group: "{{ service_group }}"
    mode: '0777'
  become: true

- name: Install MPD music scan cron
  ansible.builtin.cron:
    name: "MPD Music Library Scan"
    minute: "*/15"
    user: "{{ service_user }}"
    job: "docker exec mpd mpc update"
  become: true

- name: Create AmpD download directory
  ansible.builtin.file:
    path: "{{ services_config_path }}/Snapcast/AmpD"
    state: directory
    owner: "{{ service_user }}"
    group: "{{ service_group }}"
    mode: '0755'
  become: true

- name: Download AmpD binary
  ansible.builtin.get_url:
    url: "https://github.com/rain0r/ampd/releases/download/ampd-2.2.7/ampd.jar"
    dest: "{{ services_config_path }}/Snapcast/AmpD/ampd.jar"
    owner: "{{ service_user }}"
    group: "{{ service_group }}"
    mode: '0755'
  become: true

- name: Setup Snapcast service
  include_tasks: ../shared_tasks/tasks/init_service.yml
  vars:
    service_name: Snapcast
    config_copies:
      - src_config_path: .
    env_content: |
      CONF_PATH={{ services_config_path }}/Snapcast/snapcast.conf
      SPOTIFY_AUDIO_NAME={{ spotify_audio_name_pretty }}
      RESPOT_VOLUME_PATH={{ services_config_path }}/Snapcast/librespot
      MPD_MUSIC_PATH={{ msync_music_path }}
      MPD_DATA_PATH={{ services_data_path }}/Snapcast/MPD
      MPD_CONF_PATH={{ services_config_path }}/Snapcast/mpd.conf
      MPD_UID={{ service_uid }}
      MPD_GID={{ service_gid }}
    templates:
      - src_template_path: snapcast.conf.j2
        dst_template_path: snapcast.conf
