- name: Setup Homepage service
  include_tasks: ../../shared_tasks/tasks/init_service.yml
  vars:
    service_name: Homepage
    reverse_proxy: reverse_proxy.conf.j2
    config_copies:
      - src_config_path: .
    env_content: |
      DATA_PATH={{ services_config_path }}/Homepage/config
      HOSTNAME={{ external_hostname }}
      HOMEPAGE_DATA_VOLUME={{ homepage_data_volume }}
    templates:
      - src_template_path: services.yaml.j2
        dst_template_path: config/config/services.yaml
        file_mode: "0600"
      - src_template_path: docker.yaml.j2
        dst_template_path: config/config/docker.yaml
        file_mode: "0600"
      - src_template_path: bookmarks.yaml.j2
        dst_template_path: config/config/bookmarks.yaml
        file_mode: "0600"
