services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    user: "${PUID}:${PGID}"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}:/config
      - ${MEDIA_PATH}:/media
    restart: unless-stopped
    network_mode: "container:gluetun"
