- name: Initialize domains config
  set_fact:
    domains_config_list: []

- name: Build domains config list
  set_fact:
    domains_config_list: "{{ domains_config_list + [{'domain': item.0, 'zoneId': item.1}] }}"
  loop: "{{ managed_domains | zip(cloudflare_zone_ids) | list }}"

- name: Convert domains config to JSON
  set_fact:
    domains_config: "{{ domains_config_list | to_json }}"

- name: Setup ddns service
  import_tasks: ../shared_tasks/tasks/init_service.yml
  vars:
    service_name: ddns
    config_copies:
      - src_config_path: .
    env_content: |
      DOMAINS={{ domains_config }}
      CLOUDFLARE_API_TOKEN={{ cloudflare_ddns_api_token }}
