- name: Login to Seafile Docker registry
  ansible.builtin.shell: >
    docker login docker.seadrive.org --username "{{ seafile.docker_username }}" --password "{{ seafile_docker_password }}"
  become: true

- name: Ensure Elasticsearch data directory exists with correct permissions
  ansible.builtin.file:
    path: "{{ services_data_path }}/Seafile/elasticsearch/data"
    state: directory
    owner: 1000
    group: 0
    mode: "0755"
    recurse: true
  become: true

- name: Setup Seafile service
  include_tasks: ../../shared_tasks/tasks/init_service.yml
  vars:
    service_name: Seafile
    skip_chown_data: true
    env_content: |
      DB_PASSWORD={{ seafile_db_password }}
      ADMIN_EMAIL={{ admin_email }}
      ADMIN_PASSWORD={{ seafile_admin_password }}
      DATA_PATH={{ services_data_path }}/Seafile
      HOSTNAME=seafile.{{ external_hostname }}
      SEAFILE_CLI_LIBRARY_IDS={{ seafile_library_ids | join(',') }}
      SEAFILE_CLI_USERNAME={{ admin_email }}
      SEAFILE_CLI_TOKEN={{ seafile_client_token }}
      SEAFILE_CLI_SERVER_URL=http://seafile
      SEAFILE_CLI_CONFIG_PATH={{ services_data_path }}/Seafile/seafile-client
      SEAFILE_CLI_CLONE_PATH={{ seafile.clone_path }}
      NON_ROOT=true
    config_copies:
      - src_config_path: .

- name: Setup Seafile garbage collection cron
  ansible.builtin.cron:
    name: "Seafile garbage collection"
    minute: "40"
    hour: "4"
    job: "docker exec seafile /scripts/gc.sh"
    user: "{{ service_user }}"
  become: true
